--- 
- name: "Deploying application"
  become: true
  hosts: webservers
  tasks:
    - 
      name: "Compiling Java Application"
      shell:
        cmd: javac Hello.java
        creates: Hello.class
        chdir: /home/osboxes/Documents
    - 
      name: "Deploying Application"
      shell:
        cmd: java Hello
        chdir: /home/osboxes/Documents
      register: result

    - debug:
        var: result.stdout
